'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'fr' | 'he' | 'zh';
export type Theme = 'light' | 'dark' | 'system';

interface PreferencesContextType {
  lang: Language;
  theme: Theme;
  setLang: (lang: Language) => void;
  setTheme: (theme: Theme) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    dashboard: "Dashboard",
    k8sClusters: "K8s Clusters",
    crdControl: "K6 Operator CRDs",
    influxdb: "InfluxDB Analytics",
    settings: "Settings",
    logout: "Log out",
    connected: "Connected",
    activeAgent: "K8s Agent Active",
    secureSession: "Secured TLS 1.3 Session",
    syncTime: "Last sync",
    addCluster: "Add Cluster",
    welcome: "Welcome to K6 Stratum Portal",
    subWelcome: "Kubernetes & Performance Observability Portal",
    username: "Username",
    password: "Password",
    login: "Log In",
    ssoLogin: "Sign in with SSO",
    localLogin: "Local Login",
    ssoLoginTab: "SSO Authentication",
    defaultAccount: "Default Admin Credentials",
    verifyConn: "Verify Connection",
    status: "Status",
    save: "Save",
    cancel: "Cancel",
    clusterName: "Cluster Name",
    apiServerUrl: "API Server URL",
    authType: "Authentication Type",
    caCert: "CA Certificate (Optional, Base64)",
    crdDetails: "CRD Details",
    specObject: "Kubernetes Spec Object",
    limits: "Resource Limits (Runner)",
    newTest: "New Test",
    runs: "Runs in InfluxDB",
    telemetry: "Telemetry",
    maxVal: "Maximum Value",
    avgVal: "Average Value",
    minVal: "Minimum Value",
    settingsTitle: "Platform Settings",
    settingsSub: "Define Kubernetes clusters and InfluxDB telemetry credentials.",
    influxConfigTitle: "InfluxDB Database Connection",
    influxConfigSub: "Configure parameters used to query performance runs.",
    url: "URL",
    token: "Token",
    org: "Organization",
    bucket: "Bucket",
    accessForbidden: "Access Forbidden",
    adminRequired: "Administrator privileges are required to view this page.",
    theme: "Theme",
    lang: "Language",
    testConn: "Test Connection",
    delete: "Delete",
    runners: "Runners",
    stage: "Stage",
    createdOn: "Created On",
    details: "Details",
    crdList: "k6s.k6.io resources",
    noResources: "No Custom Resource K6 present in this namespace.",
    selectRes: "Select a resource to display its details.",
    instantiateK6: "Instantiate K6 Test",
    launchSpecDesc: "Create a Custom Resource `K6` that deploys the test architecture on the cluster.",
    runName: "Run Name (Resource Name)",
    parallelism: "Parallelism (Runners)",
    scriptConfigMap: "Script ConfigMap",
    jsFile: "JS File",
    cpuLimit: "CPU Limit",
    memLimit: "RAM Limit",
    deploying: "Deploying...",
    deploy: "Deploy",
    clustersK8s: "K8s Clusters",
    inspectClusters: "Inspect K8s API Server connectivity, infrastructure pod health, and secure configurations.",
    k8sVersion: "Kubernetes Version",
    awsRegion: "AWS Region",
    authMech: "Authentication Mechanism",
    registeredOn: "Registered On",
    active: "Active",
    checking: "Checking...",
    fail: "Failed",
    securityCheck: "Security Controls & Status",
    aesActive: "AES-256-GCM encryption active at rest",
    tlsChecked: "Kubernetes CA certificate verified",
    rbacLimit: "RBAC access restricted to test namespace",
    totalClusters: "Total K8s Clusters",
    k6SuccessRate: "K6 Success Rate",
    activeTests: "Active Tests",
    influxTelemetries: "InfluxDB Telemetries",
    recentRuns: "Recent performance runs",
    addClusterDesc: "Register cluster configuration. Sensitive credentials are encrypted via AES-256-GCM.",
    caCertDesc: "CA Certificate (Optional, Base64)",
    secretToken: "Access Token (Bearer)",
    kubeconfigYaml: "Kubeconfig (YAML Content)",
    validating: "Validating...",
    submit: "Submit",
    defaultMockCluster: "Mock Environment",
    registeredK8sClusters: "Your K8s Clusters",
    operatorStatus: "Operator Status",
    recommendations: "Help & Recommendations",
    recDesc: "Use the K6 Operator CRDs menu to schedule and monitor load runs. Consolidated performance metrics are automatically pushed to InfluxDB and viewable in the InfluxDB Analytics panel.",
    metricsTitle: "InfluxDB Analytics",
    metricsSub: "Visualize historical load runs and track http request rates and user counts.",
    metricRateToggle: "Latency (http_req_duration)",
    metricVUsToggle: "Active Users (vus)",
    valMax: "Peak Value",
    valAvg: "Average",
    valMin: "Minimum",
    chartLoading: "Loading telemetry...",
    chartNoData: "No telemetry records found.",
    chartSelectRun: "Select a test run to load performance curves.",
    savedClusters: "Connected Clusters",
    operational: "Operational",
    testRunLabel: "Test Run",
    influxSettingsSuccess: "InfluxDB configuration updated successfully.",
    influxSettingsError: "Failed to update InfluxDB configuration.",
    k8sSettingsError: "Failed to save cluster configuration.",
    k8sLoadError: "Failed to load Kubernetes clusters.",
  },
  fr: {
    dashboard: "Tableau de bord",
    k8sClusters: "Clusters K8s",
    crdControl: "CRDs K6 Operator",
    influxdb: "Analyses InfluxDB",
    settings: "Paramètres",
    logout: "Se déconnecter",
    connected: "Connecté",
    activeAgent: "Agent K8s Actif",
    secureSession: "Session TLS 1.3 Sécurisée",
    syncTime: "Dernière synchro",
    addCluster: "Ajouter un Cluster",
    welcome: "Bienvenue sur K6 Stratum Portal",
    subWelcome: "Portail d'Observabilité Kubernetes & Performance",
    username: "Identifiant",
    password: "Mot de passe",
    login: "Se connecter",
    ssoLogin: "Se connecter via le SSO",
    localLogin: "Connexion Locale",
    ssoLoginTab: "Authentification SSO",
    defaultAccount: "Compte par défaut",
    verifyConn: "Tester la connexion",
    status: "Statut",
    save: "Valider",
    cancel: "Annuler",
    clusterName: "Nom du Cluster",
    apiServerUrl: "Adresse de l'API Server (URL)",
    authType: "Type de Connexion",
    caCert: "Certificat CA (Optionnel, Base64)",
    crdDetails: "Détails du CRD",
    specObject: "Objet Spec Kubernetes",
    limits: "Limites de Ressources (Runner)",
    newTest: "Nouveau Test",
    runs: "Runs dans InfluxDB",
    telemetry: "Télémétrie",
    maxVal: "Valeur Maximale",
    avgVal: "Valeur Moyenne",
    minVal: "Valeur Minimale",
    settingsTitle: "Paramètres de la Plateforme",
    settingsSub: "Définissez les clusters Kubernetes et les identifiants de télémétrie InfluxDB.",
    influxConfigTitle: "Connexion Base InfluxDB",
    influxConfigSub: "Configurez les paramètres utilisés pour requêter les runs de performance.",
    url: "URL",
    token: "Token",
    org: "Organisation",
    bucket: "Bucket",
    accessForbidden: "Accès Interdit",
    adminRequired: "Les privilèges d'administrateur sont requis pour accéder à cette page.",
    theme: "Thème",
    lang: "Langue",
    testConn: "Tester la connexion",
    delete: "Supprimer",
    runners: "Exécuteurs",
    stage: "Étape",
    createdOn: "Créé le",
    details: "Détails",
    crdList: "Ressources k6s.k6.io",
    noResources: "Aucune ressource Custom Resource K6 présente dans ce namespace.",
    selectRes: "Sélectionnez une ressource pour afficher ses détails.",
    instantiateK6: "Instancier un Test K6",
    launchSpecDesc: "Créez une ressource Custom Resource `K6` qui déploiera l'architecture de test sur le cluster sélectionné.",
    runName: "Nom du Run (Ressource Name)",
    parallelism: "Parallélisme (Runners)",
    scriptConfigMap: "ConfigMap de Script",
    jsFile: "Fichier JS",
    cpuLimit: "Limites CPU",
    memLimit: "Limites RAM",
    deploying: "Déploiement...",
    deploy: "Déployer",
    clustersK8s: "Clusters K8s",
    inspectClusters: "Inspectez la connectivité de l'API Server, les états des pods d'infrastructure et les configurations sécurisées.",
    k8sVersion: "Version Kubernetes",
    awsRegion: "Région AWS",
    authMech: "Mécanisme d'Authentification",
    registeredOn: "Enregistré le",
    active: "Actif",
    checking: "Vérification...",
    fail: "Échec",
    securityCheck: "Contrôles de Sécurité & Statut",
    aesActive: "Chiffrement AES-256-GCM actif en base de données",
    tlsChecked: "Certificat CA Kubernetes vérifié",
    rbacLimit: "Accès RBAC limité au namespace de test",
    totalClusters: "Clusters K8s Connectés",
    k6SuccessRate: "Taux de Succès K6",
    activeTests: "Tests Actifs",
    influxTelemetries: "Télémétries InfluxDB",
    recentRuns: "Runs récents de performance",
    addClusterDesc: "Enregistrez vos configurations de cluster. Les credentials sensibles sont chiffrés à l'aide d'une clé AES-256-GCM.",
    caCertDesc: "Certificat CA (Optionnel, Base64)",
    secretToken: "Token d'accès (Bearer)",
    kubeconfigYaml: "Kubeconfig (Contenu YAML)",
    validating: "Validation...",
    submit: "Valider",
    defaultMockCluster: "Environnement Mocké",
    registeredK8sClusters: "Vos Clusters Kubernetes",
    operatorStatus: "Statut des Opérateurs",
    recommendations: "Aide & Recommandations",
    recDesc: "Utilisez les menus CRDs K6 Operator pour planifier et suivre vos exécutions de tests de charge. Les résultats de performance consolidés seront automatiquement agrégés dans InfluxDB et consultables via le panneau Analyses InfluxDB.",
    metricsTitle: "Analyses InfluxDB",
    metricsSub: "Visualisez les performances historiques et suivez l'évolution des requêtes HTTP et de la charge utilisateurs.",
    metricRateToggle: "Latence (http_req_duration)",
    metricVUsToggle: "Utilisateurs (vus)",
    valMax: "Valeur Maximale",
    valAvg: "Moyenne",
    valMin: "Valeur Minimale",
    chartLoading: "Chargement du graphique...",
    chartNoData: "Pas de données graphiques.",
    chartSelectRun: "Sélectionnez un test run pour charger les graphes de télémétrie.",
    savedClusters: "Clusters Connectés",
    operational: "Opérationnels",
    testRunLabel: "Test Run",
    influxSettingsSuccess: "Configuration InfluxDB mise à jour avec succès.",
    influxSettingsError: "Échec de la mise à jour de la configuration InfluxDB.",
    k8sSettingsError: "Échec de la configuration du cluster.",
    k8sLoadError: "Échec du chargement des clusters Kubernetes.",
  },
  he: {
    dashboard: "לוח בקרה",
    k8sClusters: "K8s Clusters",
    crdControl: "CRDs של K6 Operator",
    influxdb: "אנליטיקת InfluxDB",
    settings: "הגדרות",
    logout: "התנתק",
    connected: "מחובר",
    activeAgent: "סוכן K8s פעיל",
    secureSession: "סשן TLS 1.3 מאובטח",
    syncTime: "סנכרון אחרון",
    addCluster: "הוסף אשכול",
    welcome: "ברוכים הבאים ל-K6 Stratum Portal",
    subWelcome: "פורטל ניטור ביצועים וקיברנטיס",
    username: "שם משתמש",
    password: "סיסמה",
    login: "התחבר",
    ssoLogin: "התחברות באמצעות SSO",
    localLogin: "התחברות מקומית",
    ssoLoginTab: "אימות SSO",
    defaultAccount: "חשבון מנהל ברירת מחדל",
    verifyConn: "בדוק חיבור",
    status: "סטטוס",
    save: "שמור",
    cancel: "ביטול",
    clusterName: "שם האשכול",
    apiServerUrl: "כתובת שרת ה-API",
    authType: "סוג אימות",
    caCert: "אישור CA (אופציונלי, Base64)",
    crdDetails: "פרטי CRD",
    specObject: "אובייקט Spec של קיברנטיס",
    limits: "מגבלות משאבים (Runner)",
    newTest: "בדיקה חדשה",
    runs: "הרצות ב-InfluxDB",
    telemetry: "טלמטריה",
    maxVal: "ערך מקסימלי",
    avgVal: "ערך ממוצע",
    minVal: "ערך מינימלי",
    settingsTitle: "הגדרות פלטפורמה",
    settingsSub: "הגדר אשכולות קיברנטיס ופרטי גישה ל-InfluxDB.",
    influxConfigTitle: "חיבור למסד נתונים InfluxDB",
    influxConfigSub: "הגדר פרמטרים לשאילתות הרצת ביצועים.",
    url: "כתובת URL",
    token: "אסימון (Token)",
    org: "ארגון (Org)",
    bucket: "באקט (Bucket)",
    accessForbidden: "הגישה נחסמה",
    adminRequired: "נדרשות הרשאות מנהל כדי לצפות בדף זה.",
    theme: "ערכת נושא",
    lang: "שפה",
    testConn: "בדוק חיבור",
    delete: "מחק",
    runners: "רצים",
    stage: "שלב",
    createdOn: "נוצר ב",
    details: "פרטים",
    crdList: "משאבי k6s.k6.io",
    noResources: "אין משאבי K6 בNamespace זה.",
    selectRes: "בחר משאב להצגת פרטים.",
    instantiateK6: "צור בדיקת K6 חדשה",
    launchSpecDesc: "צור משאב K6 חדש לפריסת בדיקת העומס באשכול.",
    runName: "שם הבדיקה",
    parallelism: "מקביליות (Runners)",
    scriptConfigMap: "Script ConfigMap",
    jsFile: "קובץ JS",
    cpuLimit: "מגבלת CPU",
    memLimit: "מגבלת RAM",
    deploying: "פורס...",
    deploy: "פרוס בדיקה",
    clustersK8s: "K8s Clusters",
    inspectClusters: "בדוק חיבור לשרת ה-API של K8s, בריאות הפודים והגדרות אבטחה.",
    k8sVersion: "גרסת קיברנטיס",
    awsRegion: "אזור AWS",
    authMech: "מנגנון אימות",
    registeredOn: "נרשם ב",
    active: "פעיל",
    checking: "בודק...",
    fail: "נכשל",
    securityCheck: "בקרות אבטחה וסטטוס",
    aesActive: "הצפנת AES-256-GCM פעילה",
    tlsChecked: "אישור CA של קיברנטיס מאומת",
    rbacLimit: "גישת RBAC מוגבלת לNamespace של הבדיקה",
    totalClusters: "סך הכל K8s Clusters",
    k6SuccessRate: "שיעור הצלחה K6",
    activeTests: "בדיקות פעילות",
    influxTelemetries: "חיבורי InfluxDB",
    recentRuns: "הרצות ביצועים אחרונות",
    addClusterDesc: "רשום הגדרות אשכול. פרטי גישה רגישים מוצפנים ב-AES-256-GCM.",
    caCertDesc: "אישור CA (אופציונלי, Base64)",
    secretToken: "אסימון גישה (Bearer)",
    kubeconfigYaml: "קובץ Kubeconfig (תוכן YAML)",
    validating: "מאמת...",
    submit: "שלח",
    defaultMockCluster: "סביבה מדומה",
    registeredK8sClusters: "אשכולות הקיברנטיס שלך",
    operatorStatus: "סטטוס מפעילים (Operators)",
    recommendations: "עזרה והמלצות",
    recDesc: "השתמש בתפריט CRDs של K6 Operator כדי לתזמן ולעקוב אחר בדיקות עומס. מדדי ביצועים נשמרים ב-InfluxDB וזמינים בדף אנליטיקת InfluxDB.",
    metricsTitle: "אנליטיקת InfluxDB",
    metricsSub: "צפה בהרצות ביצועים היסטוריות ועקוב אחר קצב בקשות HTTP וכמות משתמשים.",
    metricRateToggle: "זמן תגובה (http_req_duration)",
    metricVUsToggle: "משתמשים פעילים (vus)",
    valMax: "ערך שיא",
    valAvg: "ממוצע",
    valMin: "מינימום",
    chartLoading: "טוען נתונים...",
    chartNoData: "לא נמצאו נתוני טלמטריה.",
    chartSelectRun: "בחר הרצה לטעינת גרף ביצועים.",
    savedClusters: "אשכולות מחוברים",
    operational: "פעיל ומבצעי",
    testRunLabel: "הרצת בדיקה",
    influxSettingsSuccess: "הגדרות InfluxDB עודכנו בהצלחה.",
    influxSettingsError: "עדכון הגדרות InfluxDB נכשל.",
    k8sSettingsError: "שמירת הגדרות האשכול נכשלה.",
    k8sLoadError: "טעינת אשכולות קיברנטיס נכשלה.",
  },
  zh: {
    dashboard: "仪表板",
    k8sClusters: "K8s 集群",
    crdControl: "K6 算子 CRD",
    influxdb: "InfluxDB 分析",
    settings: "设置",
    logout: "登出",
    connected: "已连接",
    activeAgent: "K8s 代理已激活",
    secureSession: "安全 TLS 1.3 会话",
    syncTime: "上次同步",
    addCluster: "添加集群",
    welcome: "欢迎使用 K6 Stratum Portal",
    subWelcome: "Kubernetes 与性能观测门户",
    username: "用户名",
    password: "密码",
    login: "登录",
    ssoLogin: "通过 SSO 登录",
    localLogin: "本地登录",
    ssoLoginTab: "SSO 身份验证",
    defaultAccount: "默认管理员账户",
    verifyConn: "测试连接",
    status: "状态",
    save: "保存",
    cancel: "取消",
    clusterName: "集群名称",
    apiServerUrl: "API 服务器 URL",
    authType: "认证类型",
    caCert: "CA 证书（可选，Base64）",
    crdDetails: "CRD 详情",
    specObject: "Kubernetes Spec 对象",
    limits: "资源限制 (Runner)",
    newTest: "新建测试",
    runs: "InfluxDB 运行记录",
    telemetry: "遥测",
    maxVal: "最大值",
    avgVal: "平均值",
    minVal: "最小值",
    settingsTitle: "平台设置",
    settingsSub: "定义 Kubernetes 集群与 InfluxDB 遥测凭据。",
    influxConfigTitle: "InfluxDB 数据库连接",
    influxConfigSub: "配置用于查询性能运行记录的参数。",
    url: "URL地址",
    token: "访问令牌 (Token)",
    org: "组织 (Org)",
    bucket: "存储桶 (Bucket)",
    accessForbidden: "拒绝访问",
    adminRequired: "查看此页面需要管理员权限。",
    theme: "主题",
    lang: "语言",
    testConn: "测试连接",
    delete: "删除",
    runners: "执行器 (Runners)",
    stage: "阶段",
    createdOn: "创建时间",
    details: "详情",
    crdList: "k6s.k6.io 资源列表",
    noResources: "在此命名空间中未找到 K6 自定义资源。",
    selectRes: "选择一个资源以显示其详细信息。",
    instantiateK6: "实例化 K6 测试",
    launchSpecDesc: "创建一个自定义资源 `K6`，在集群上部署负载测试架构。",
    runName: "测试运行名称",
    parallelism: "并发数 (Runners)",
    scriptConfigMap: "脚本 ConfigMap",
    jsFile: "JS 脚本文件",
    cpuLimit: "CPU 限制",
    memLimit: "内存限制",
    deploying: "部署中...",
    deploy: "部署测试",
    clustersK8s: "K8s 集群",
    inspectClusters: "检查 K8s API 服务器连接性、基础设施 Pod 健康状况和安全配置。",
    k8sVersion: "Kubernetes 版本",
    awsRegion: "AWS 区域",
    authMech: "认证机制",
    registeredOn: "注册时间",
    active: "正常运行",
    checking: "检查中...",
    fail: "失败",
    securityCheck: "安全控制与状态",
    aesActive: "AES-256-GCM 静态加密已启用",
    tlsChecked: "Kubernetes CA 证书已验证",
    rbacLimit: "RBAC 权限仅限于测试命名空间",
    totalClusters: "K8s 集群总数",
    k6SuccessRate: "K6 测试成功率",
    activeTests: "活动测试数",
    influxTelemetries: "InfluxDB 连接数",
    recentRuns: "最近的性能测试",
    addClusterDesc: "注册集群配置。敏感凭据已通过 AES-256-GCM 加密。",
    caCertDesc: "CA 证书 (Base64)",
    secretToken: "访问令牌 (Bearer)",
    kubeconfigYaml: "Kubeconfig (YAML 格式)",
    validating: "验证中...",
    submit: "提交",
    defaultMockCluster: "模拟环境",
    registeredK8sClusters: "您的 Kubernetes 集群",
    operatorStatus: "算子组件状态",
    recommendations: "使用帮助与建议",
    recDesc: "使用 K6 Operator CRDs 菜单调度和监视负载测试。汇总的性能指标会自动写入 InfluxDB，并可在 InfluxDB 分析面板中查看。",
    metricsTitle: "InfluxDB 数据分析",
    metricsSub: "可视化历史测试运行，跟踪 HTTP 请求速率和活跃用户数。",
    metricRateToggle: "请求延迟 (http_req_duration)",
    metricVUsToggle: "活跃用户数 (vus)",
    valMax: "峰值",
    valAvg: "平均值",
    valMin: "最小值",
    chartLoading: "加载遥测数据中...",
    chartNoData: "未找到遥测记录。",
    chartSelectRun: "选择一个测试运行记录以加载性能曲线图。",
    savedClusters: "已连接的集群",
    operational: "正常就绪",
    testRunLabel: "测试运行",
    influxSettingsSuccess: "InfluxDB 配置更新成功。",
    influxSettingsError: "更新 InfluxDB 配置失败。",
    k8sSettingsError: "保存集群配置失败。",
    k8sLoadError: "加载 Kubernetes 集群失败。",
  }
};

const PreferencesContext = createContext<PreferencesContextType | undefined>(undefined);

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('en');
  const [theme, setThemeState] = useState<Theme>('dark');

  // Load from local storage
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('pref-lang') as Language;
      const savedTheme = localStorage.getItem('pref-theme') as Theme;
      if (savedLang) setLangState(savedLang);
      if (savedTheme) setThemeState(savedTheme);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('pref-lang', newLang);
  };

  const setTheme = (newTheme: Theme) => {
    setThemeState(newTheme);
    localStorage.setItem('pref-theme', newTheme);
  };

  // Sync theme with document element attribute
  useEffect(() => {
    const root = document.documentElement;
    if (theme === 'system') {
      root.setAttribute('data-theme', 'system');
    } else {
      root.setAttribute('data-theme', theme);
    }
  }, [theme]);

  const t = (key: string): string => {
    const dict = translations[lang] || translations['en'];
    return (dict as any)[key] || key;
  };

  return (
    <PreferencesContext.Provider value={{ lang, theme, setLang, setTheme, t }}>
      {children}
    </PreferencesContext.Provider>
  );
}

export function usePreferences() {
  const context = useContext(PreferencesContext);
  if (!context) {
    throw new Error('usePreferences must be used within a PreferencesProvider');
  }
  return context;
}
